version: 2.1
orbs:
  node: circleci/node@18.14.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/node_modules
          override-ci-command: npm install
      - checkout
      - run: npm start
workflows:
  test_my_app:
    jobs:
      - test