version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/node_modules
          override-ci-command: npm install
      - checkout
      #- run: sudo apt install gulp
      #- node/install-packages:
          #override-ci-command: sudo apt install libnss3-dev libxss1
      - run: npm start
workflows:
  test_my_app:
    jobs:
      - test