version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/node_modules
          override-ci-command: npm install
      - run: apt-get update && apt-get install -y libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libasound2
      - run: npm start
workflows:
  test_my_app:
    jobs:
      - test